on:
  push:
   
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
      - name: " building docker "
        run: docker build -t ${{ secrets.USERNAME }}/ahmed .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.USERNAME }}/ahmed


